#!/usr/bin/env bash
# This script install nginx, configures it and serve a "hello world"
sudo apt-get update
sudo apt-get -y install nginx
echo 'Hello World!' > /var/www/html/index.html
service nginx start
