#!/usr/bin/env bash
# This Create a script to install and configure HAProxy on lb-01 server
# and also configure HAProxy to send traffic to web-01 and web-02 servers
# to distribute requests using a roundrobin algorithm
# and make sure that HAProxy can be managed via an init script
# also install and configure HAproxy on my lb-01 server.
sudo apt-get -y update
apt-get -y install haproxy

# editting config file
server_config=\
"
frontend  smartcodez-frontend
        bind *:80
        mode http
        default_backend smartcodez-backend
backend smartcodez-backend
        balance roundrobin
        server 52736-web-01 52.91.154.135:80 check
        server 52736-web-02 54.87.207.246:80 check
"
echo "$server_config" | sudo tee -a /etc/haproxy/haproxy.cfg

# enable haproxy to be started by init script

echo "ENABLED=1" | sudo tee -a /etc/default/haproxy

sudo service haproxy restart

